#!/usr/bin/env bash
#
# bootstrap installs things.

DOTFILES_ROOT="$HOME/.dotfiles"

set -e

echo ''

info () {
    printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
    printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
    echo ''
    exit
}

link_files () {
    ln -s $1 $2
    success "linked $1 to $2"
}

install_dotfiles () {
    info 'installing dotfiles'

    for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
    do
	dest="$HOME/.`basename \"${source%.*}\"`"

        rm -rf $dest
        link_files $source $dest
    done
}

compile_emacs_packages() {
    info 'compiling emacs packages'

    # Compile cedet
    cd $DOTFILES_ROOT/emacs/emacs.d.symlink/my-packages/cedet && make

    # Compile auto-complete
    cd $DOTFILES_ROOT/emacs/emacs.d.symlink/my-packages/auto-complete && make byte-compile
}

compile_emacs_packages
echo ' '
echo '  Linking files'
echo ' '
install_dotfiles

echo ''
echo '  All installed!'
