#!/usr/bin/env bash
#
# bootstrap installs things.

DOTFILES_ROOT="$HOME/.dotfiles"

set -e

link_files () {
    if [[ ! -e $2 ]]
    then
	ln -s $1 $2
	echo "linked $1 to $2"
    fi
}


echo ' '
echo '  Linking bash config'
echo ' '

link_files "$DOTFILES_ROOT/bash/.bashrc" "$HOME/.bashrc"
link_files "$DOTFILES_ROOT/bash/.dir_colors" "$HOME/.dir_colors"


echo ' '
echo ' Getting emacs packages'
echo ' '

if [[ ! -e ~/.cask ]]
then
    echo "Cloning Cask repo"
    git clone https://github.com/cask/cask.git ~/.cask
fi

mkdir -p ~/.emacs.d
link_files "$DOTFILES_ROOT/emacs/Cask" "$HOME/.emacs.d/Cask"
cd ~/.emacs.d && $HOME/.cask/bin/cask install
link_files "$DOTFILES_ROOT/emacs/site-lisp" "$HOME/.emacs.d/site-lisp"

echo ' '
echo ' Linking emacs config'

mkdir -p "$HOME/.emacs.d/auto-save-files"
mkdir -p "$HOME/.emacs.d/auto-save-list"
mkdir -p "$HOME/.emacs.d/backup-files"

link_files "$DOTFILES_ROOT/emacs/config" "$HOME/.emacs.d/config"
link_files "$DOTFILES_ROOT/emacs/ecb-user-layouts.el" "$HOME/.ecb-user-layouts.el"
link_files "$DOTFILES_ROOT/emacs/ecb-tip-of-day.el" "$HOME/.ecb-tip-of-day.el"
link_files "$DOTFILES_ROOT/emacs/init.el" "$HOME/.emacs.d/init.el"
touch "$HOME/.emacs.d/custom.el"

echo ' '
echo '  All installed!'
