#!/usr/bin/env bash

get_emacs_packages() {

    info 'getting emacs packages'

    info 'getting cedet'
    if [[ ! -d "$DOTFILES_ROOT/emacs/emacs.d.symlink/my-packages/cedet" ]]; then
	cd $DOTFILES_ROOT/emacs/emacs.d.symlink/my-packages && git clone http://git.randomsample.de/cedet.git cedet && cd cedet && git submodule init && git submodule update
    fi

    info 'getting auto-complete'
    if [[ ! -d "$DOTFILES_ROOT/emacs/emacs.d.symlink/my-packages/auto-complete" ]]; then
	cd $DOTFILES_ROOT/emacs/emacs.d.symlink/my-packages && git clone https://github.com/auto-complete/auto-complete.git auto-complete && cd auto-complete && git submodule init && git submodule update
    fi

    info 'getting yasnippet'
    if [[ ! -d "$DOTFILES_ROOT/emacs/emacs.d.symlink/my-packages/yasnippet" ]]; then
	cd $DOTFILES_ROOT/emacs/emacs.d.symlink/my-packages && git clone --recursive https://github.com/capitaomorte/yasnippet yasnippet
    fi

    info 'getting yasnippets-latex'
    if [[ ! -d "$DOTFILES_ROOT/emacs/emacs.d.symlink/my-packages/yasnippets-latex" ]]; then
	cd $DOTFILES_ROOT/emacs/emacs.d.symlink/my-packages && git clone https://github.com/madsdk/yasnippets-latex.git yasnippets-latex
    fi

    info 'getting emacs-color-theme-solarized'
    if [[ ! -d "$DOTFILES_ROOT/emacs/emacs.d.symlink/my-packages/emacs-color-theme-solarized" ]]; then
	cd $DOTFILES_ROOT/emacs/emacs.d.symlink/my-packages && git clone https://github.com/sellout/emacs-color-theme-solarized.git emacs-color-theme-solarized
    fi

    info 'getting highlight-parentheses'
    if [[ ! -d "$DOTFILES_ROOT/emacs/emacs.d.symlink/my-packages/highlight-parentheses" ]]; then
	cd $DOTFILES_ROOT/emacs/emacs.d.symlink/my-packages && git clone https://github.com/nschum/highlight-parentheses.el.git highlight-parentheses
    fi
}

get_emacs_packages
